import type { CapitalsInterface } from "../interfaces/interface.interfaces";

export const capitals: Array<CapitalsInterface> = [
  { id: 1, fa: "تهران", en: "Tehran", name: "Tehran" },
  { id: 2, fa: "کابل", en: "Kabul", name: "Kabul" },
  { id: 3, fa: "اسلام‌آباد", en: "Islamabad", name: "Islamabad" },
  { id: 4, fa: "دهلی نو", en: "New Delhi", name: "NewDelhi" },
  { id: 5, fa: "پکن", en: "Beijing", name: "Beijing" },
  { id: 6, fa: "توکیو", en: "Tokyo", name: "Tokyo" },
  { id: 7, fa: "سئول", en: "Seoul", name: "Seoul" },
  { id: 8, fa: "بانکوک", en: "Bangkok", name: "Bangkok" },
  { id: 9, fa: "کوالالامپور", en: "Kuala Lumpur", name: "KualaLumpur" },
  { id: 10, fa: "جاکارتا", en: "Jakarta", name: "Jakarta" },
  { id: 11, fa: "سنگاپور", en: "Singapore", name: "Singapore" },
  { id: 12, fa: "کاتماندو", en: "Kathmandu", name: "Kathmandu" },
  { id: 13, fa: "باکو", en: "Baku", name: "Baku" },
  { id: 14, fa: "تفلیس", en: "Tbilisi", name: "Tbilisi" },
  { id: 15, fa: "مسکو", en: "Moscow", name: "Moscow" },
  { id: 16, fa: "آنکارا", en: "Ankara", name: "Ankara" },
  { id: 17, fa: "بغداد", en: "Baghdad", name: "Baghdad" },
  { id: 18, fa: "دمشق", en: "Damascus", name: "Damascus" },
  { id: 19, fa: "بیروت", en: "Beirut", name: "Beirut" },
  { id: 20, fa: "قدس", en: "Jerusalem", name: "Jerusalem" },
  { id: 21, fa: "قاهره", en: "Cairo", name: "Cairo" },
  { id: 22, fa: "طرابلس", en: "Tripoli", name: "Tripoli" },
  { id: 23, fa: "الجزیره", en: "Algiers", name: "Algiers" },
  { id: 24, fa: "رباط", en: "Rabat", name: "Rabat" },
  { id: 25, fa: "خرطوم", en: "Khartoum", name: "Khartoum" },
  { id: 26, fa: "پاریس", en: "Paris", name: "Paris" },
  { id: 27, fa: "لندن", en: "London", name: "London" },
  { id: 28, fa: "برلین", en: "Berlin", name: "Berlin" },
  { id: 29, fa: "رم", en: "Rome", name: "Rome" },
  { id: 30, fa: "مادرید", en: "Madrid", name: "Madrid" },
  { id: 31, fa: "آتن", en: "Athens", name: "Athens" },
  { id: 32, fa: "آمستردام", en: "Amsterdam", name: "Amsterdam" },
  { id: 33, fa: "بروکسل", en: "Brussels", name: "Brussels" },
  { id: 34, fa: "وین", en: "Vienna", name: "Vienna" },
  { id: 35, fa: "استکهلم", en: "Stockholm", name: "Stockholm" },
  { id: 36, fa: "کپنهاگ", en: "Copenhagen", name: "Copenhagen" },
  { id: 37, fa: "اوسلو", en: "Oslo", name: "Oslo" },
  { id: 38, fa: "هلسینکی", en: "Helsinki", name: "Helsinki" },
  { id: 39, fa: "ورشو", en: "Warsaw", name: "Warsaw" },
  { id: 40, fa: "بوداپست", en: "Budapest", name: "Budapest" },
  { id: 41, fa: "پراگ", en: "Prague", name: "Prague" },
  { id: 42, fa: "براتیسلاوا", en: "Bratislava", name: "Bratislava" },
  { id: 43, fa: "زوریخ", en: "Zurich", name: "Zurich" },
  { id: 44, fa: "برن", en: "Bern", name: "Bern" },
  { id: 45, fa: "واشنگتن", en: "Washington D.C.", name: "WashingtonDC" },
  { id: 46, fa: "اوتاوا", en: "Ottawa", name: "Ottawa" },
  { id: 47, fa: "مکزیکوسیتی", en: "Mexico City", name: "MexicoCity" },
  { id: 48, fa: "برازیلیا", en: "Brasilia", name: "Brasilia" },
  { id: 49, fa: "بوئنوس آیرس", en: "Buenos Aires", name: "BuenosAires" },
  { id: 50, fa: "سانتیاگو", en: "Santiago", name: "Santiago" },
  { id: 51, fa: "لیما", en: "Lima", name: "Lima" },
  { id: 52, fa: "مونته‌ویدئو", en: "Montevideo", name: "Montevideo" },
  { id: 53, fa: "هاوانا", en: "Havana", name: "Havana" },
  { id: 54, fa: "کاراکاس", en: "Caracas", name: "Caracas" },
  { id: 55, fa: "کیتو", en: "Quito", name: "Quito" },
  { id: 56, fa: "بوگوتا", en: "Bogota", name: "Bogota" },
  { id: 57, fa: "کانبرا", en: "Canberra", name: "Canberra" },
  { id: 58, fa: "ولینگتون", en: "Wellington", name: "Wellington" },
  { id: 59, fa: "پورت مورسبی", en: "Port Moresby", name: "PortMoresby" },
  { id: 60, fa: "پرتوریا", en: "Pretoria", name: "Pretoria" },
];
